//! Embeds the demo fixtures (`fixtures/<name>/v1`, `v2`) into the binary.
//!
//! `ripplepath demo` used to look for `fixtures/` in the current directory first, so running it
//! inside an untrusted checkout would build the demo from that checkout's files (symlinks
//! included) and run `git` on the result. Embedding makes the demo independent of the current
//! directory and of where the binary was installed.

// A build script reports problems by failing the build; there is no caller to return errors to.
#![allow(clippy::expect_used)]

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

const DEMOS: &[&str] = &["java-banking", "typescript-checkout"];
const SNAPSHOTS: &[&str] = &["v1", "v2"];

fn main() {
    let manifest = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("set by cargo"));
    let fixtures = manifest.join("../../fixtures");
    let mut out = String::from("// Generated by build.rs.\n");
    for demo in DEMOS {
        let constant = demo.to_uppercase().replace('-', "_");
        let _ = writeln!(out, "pub static {constant}: &[(&str, &[(&str, &[u8])])] = &[");
        for snapshot in SNAPSHOTS {
            let dir = fixtures.join(demo).join(snapshot);
            println!("cargo:rerun-if-changed={}", dir.display());
            let mut files = Vec::new();
            collect(&dir, "", &mut files);
            files.sort();
            let _ = writeln!(out, "    ({snapshot:?}, &[");
            for (relative, absolute) in files {
                let absolute = absolute.canonicalize().expect("fixture file exists");
                println!("cargo:rerun-if-changed={}", absolute.display());
                let _ = writeln!(out, "        ({relative:?}, include_bytes!({:?})),", absolute.display().to_string());
            }
            let _ = writeln!(out, "    ]),");
        }
        let _ = writeln!(out, "];");
    }
    let target = PathBuf::from(std::env::var_os("OUT_DIR").expect("set by cargo")).join("demo_fixtures.rs");
    std::fs::write(target, out).expect("OUT_DIR is writable");
}

fn collect(dir: &Path, prefix: &str, out: &mut Vec<(String, PathBuf)>) {
    let entries = std::fs::read_dir(dir).unwrap_or_else(|e| panic!("cannot read fixture {}: {e}", dir.display()));
    for entry in entries {
        let entry = entry.expect("readable fixture entry");
        let name = entry.file_name().to_string_lossy().into_owned();
        let relative = if prefix.is_empty() { name } else { format!("{prefix}/{name}") };
        let kind = entry.file_type().expect("fixture file type");
        assert!(!kind.is_symlink(), "fixture {relative} is a symlink; fixtures must be plain files");
        if kind.is_dir() {
            collect(&entry.path(), &relative, out);
        } else {
            out.push((relative, entry.path()));
        }
    }
}
